try {
    console.log(x);
} catch (err) {
    console.log(err.message);
}